version: "3.7"
services:
  main:
    build: .
    tty: true
    ports:
      - 23143:5678
    volumes:
      - ../../:/code
      - root-cache:/root/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  root-cache:
