version: "3.7"
services:
  main:
    build: .
    tty: true
    volumes:
      - ../../:/code
      - root-cache:/root/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  root-cache:
